### ISSUE TITLE
Traducciones y gráficos VGA

### ISSUE THREAD

**Issue by luzbel** [ibaca/la-abadia-del-crimen#1]
Entiendo que el código está basado en Vigasoco. 

Esta versión extendida de Vigasoco https://github.com/luzbel/VigasocoSDL usa los gráficos mejorados del remake de Antonio Giner , las traducciones , añade sonido y permite cargar/grabar partidas por lo que entiendo que se podrían llevar estos cambios a la versión Java

**Comment by ibaca** [comment]
Pero en este repo, o al menos yo, solo mantengo la compatibilidad con GWT para poder cargarlo en el browser. Por aquí está el que hizo el port a java (@pgpego), siempre puedes animarle a que siga haciendo mejoras o puedes hacer un MR tú mismo 😉. ¡Los problemas con GWT me encargo yo!
