### ISSUE TITLE
Pausa en el diálogo

### ISSUE THREAD

**Issue by Ygarr** [ibaca/la-abadia-del-crimen#3]
Bonito juego genial pero si no eres nativo español los diálogos pasan demasiado rápido.

Puede ser útil añadir un mecanismo para regular el tiempo de visualización de los mensajes

**Comment by ibaca** [comment]
Sorry, es una adaptación de un juego clásico que se desarrolló en España. No creo que se hagan mejoras, además el objetivo de este repo se centra en adaptar el código java a GWT.
